"""
Tests for src/auth/tokens.py — HMAC-SHA256-signed session tokens.

Each test pins AUTH_SECRET_KEY and AIOPS_DATA_DIR (tmp) via monkeypatch so no
state leaks between tests or into the repo data dir.
"""

import base64
import json
import time
from types import SimpleNamespace
from unittest.mock import MagicMock

import pytest

from src.auth import deps, store, tokens


@pytest.fixture
def auth_env(tmp_path, monkeypatch):
    monkeypatch.setenv("AIOPS_DATA_DIR", str(tmp_path))
    monkeypatch.setenv("AUTH_SECRET_KEY", "test-secret-key-for-tokens")
    yield tmp_path


def _user(token_version: int = 1) -> SimpleNamespace:
    return SimpleNamespace(
        id="user-id-123", username="alice", role="user", token_version=token_version
    )


class TestSignVerify:
    def test_sign_then_verify_roundtrip(self, auth_env):
        token = tokens.sign_session(_user())
        claims = tokens.verify_session(token)
        assert claims is not None
        assert claims["sub"] == "user-id-123"
        assert claims["name"] == "alice"
        assert claims["role"] == "user"
        assert claims["tv"] == 1
        assert claims["exp"] > time.time()

    def test_token_is_two_base64url_segments(self, auth_env):
        token = tokens.sign_session(_user())
        payload_b64, sig_b64 = token.split(".")
        padded = payload_b64 + "=" * (-len(payload_b64) % 4)
        payload = json.loads(base64.urlsafe_b64decode(padded))
        assert set(payload) == {"sub", "name", "role", "tv", "exp"}
        assert sig_b64  # non-empty signature segment

    def test_expired_token_rejected(self, auth_env):
        token = tokens.sign_session(_user(), ttl_seconds=-5)
        assert tokens.verify_session(token) is None

    def test_custom_ttl_respected(self, auth_env):
        token = tokens.sign_session(_user(), ttl_seconds=60)
        claims = tokens.verify_session(token)
        assert claims is not None
        assert claims["exp"] <= int(time.time()) + 61


class TestTampering:
    def test_tampered_payload_rejected(self, auth_env):
        token = tokens.sign_session(_user())
        payload_b64, sig_b64 = token.split(".")
        # Forge an admin payload but keep the original signature.
        padded = payload_b64 + "=" * (-len(payload_b64) % 4)
        claims = json.loads(base64.urlsafe_b64decode(padded))
        claims["role"] = "admin"
        forged = (
            base64.urlsafe_b64encode(
                json.dumps(claims, separators=(",", ":"), sort_keys=True).encode()
            )
            .rstrip(b"=")
            .decode()
        )
        assert tokens.verify_session(f"{forged}.{sig_b64}") is None

    def test_tampered_signature_rejected(self, auth_env):
        token = tokens.sign_session(_user())
        payload_b64, sig_b64 = token.split(".")
        flipped = ("A" if sig_b64[0] != "A" else "B") + sig_b64[1:]
        assert tokens.verify_session(f"{payload_b64}.{flipped}") is None

    @pytest.mark.parametrize("bad", ["", "no-dot-here", "a.b.c", ".", "x.", ".y", None])
    def test_structurally_invalid_tokens_rejected(self, auth_env, bad):
        assert tokens.verify_session(bad) is None

    def test_wrong_key_rejected(self, auth_env, monkeypatch):
        token = tokens.sign_session(_user())
        monkeypatch.setenv("AUTH_SECRET_KEY", "a-completely-different-key")
        assert tokens.verify_session(token) is None


class TestSecretFileFallback:
    def test_secret_autogenerated_when_env_unset(self, tmp_path, monkeypatch):
        monkeypatch.setenv("AIOPS_DATA_DIR", str(tmp_path))
        monkeypatch.delenv("AUTH_SECRET_KEY", raising=False)
        token = tokens.sign_session(_user())
        assert tokens.verify_session(token) is not None
        key_file = tmp_path / "auth_secret.key"
        assert key_file.exists()
        assert len(key_file.read_text(encoding="utf-8").strip()) == 64  # token_hex(32)


class TestTokenVersionMismatch:
    def test_stale_tv_rejected_by_dependency_layer(self, tmp_path, monkeypatch):
        """tv freshness is enforced by deps.get_current_user against the store."""
        monkeypatch.setenv("AIOPS_DATA_DIR", str(tmp_path))
        monkeypatch.setenv("AUTH_SECRET_KEY", "test-secret-key-for-tokens")
        store.init_db()
        record = store.create_user("carol", "carols-long-password", role="user")
        token = tokens.sign_session(record)

        request = MagicMock()
        request.cookies = {tokens.COOKIE_NAME: token}
        request.headers = {}
        assert deps.get_current_user(request) is not None

        store.bump_token_version("carol")
        assert deps.get_current_user(request) is None
