import { useCallback, useEffect, useState } from 'react'
import {
  Loader2,
  Sparkles,
  Save,
  RotateCcw,
  RefreshCw,
  Network,
  AlertTriangle,
  CheckCircle,
  Info,
} from 'lucide-react'

/**
 * Settings → Topology Schema editor.
 *
 * The platform-topology schema (what the Command Center "Platform" graph draws)
 * can be edited by hand OR generated by the 14B Reasoning Agent from a natural
 * language prompt. Flow = Preview + Apply with fallback:
 *   - "Generate preview" asks the model for a candidate; the backend validates it
 *     against the strict shape and returns it WITHOUT applying (so a bad
 *     generation can never break the live view).
 *   - "Apply" PUTs the JSON; the backend re-validates and only then makes it live.
 *   - "Reset to discovered" always restores the auto-discovered topology.
 *
 * Uses raw fetch (like the System Prompts editor) so the structured 422
 * validation errors surface verbatim instead of an opaque status code.
 */

interface SchemaNodeInput {
  id: string
  label: string
  kind: string
  tier: number
  port?: number | null
  description?: string | null
}

interface SchemaEdgeInput {
  source: string
  target: string
  relationship: string
  kind: string
}

interface SchemaDoc {
  mode: 'discovered' | 'custom'
  nodes: SchemaNodeInput[]
  edges: SchemaEdgeInput[]
}

interface GenerateResponse {
  nodes: SchemaNodeInput[]
  edges: SchemaEdgeInput[]
  note?: string
}

const ALLOWED_KINDS = 'gateway, frontend, backend, datastore, observability, llm, edge, edge-host'

interface TopologySchemaEditorProps {
  /**
   * Optional "generate from what you entered" action shown above the AI prompt
   * generator (the setup wizard uses it to seed a schema from the services the
   * user just listed). Absent in the Settings usage, where behaviour is
   * unchanged. ``run`` returns the same preview shape as the AI generator.
   */
  extraGenerator?: {
    label: string
    description: string
    run: () => Promise<GenerateResponse>
  }
  /** Called after a schema is successfully applied (the wizard advances on it). */
  onApplied?: () => void
}

/** Pull `{message, errors[]}` out of a 422 body; fall back to the status code. */
async function readError(res: Response): Promise<string> {
  try {
    const data: unknown = await res.json()
    if (data && typeof data === 'object') {
      const detail = (data as Record<string, unknown>).detail
      if (detail && typeof detail === 'object') {
        const d = detail as Record<string, unknown>
        const msg = typeof d.message === 'string' ? d.message : 'Invalid schema'
        const errs = Array.isArray(d.errors) ? (d.errors as unknown[]).map(String) : []
        return errs.length > 0 ? `${msg}: ${errs.join('; ')}` : msg
      }
      if (typeof detail === 'string') return detail
    }
  } catch {
    // non-JSON body
  }
  return `HTTP ${res.status}`
}

export function TopologySchemaEditor({
  extraGenerator,
  onApplied,
}: TopologySchemaEditorProps = {}) {
  const [mode, setMode] = useState<'discovered' | 'custom'>('discovered')
  const [jsonText, setJsonText] = useState('')
  const [prompt, setPrompt] = useState('')
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [extraGenerating, setExtraGenerating] = useState(false)
  const [syncing, setSyncing] = useState(false)
  const [applying, setApplying] = useState(false)
  const [isPreview, setIsPreview] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)

  const setDoc = (doc: SchemaDoc) => {
    setMode(doc.mode)
    setJsonText(JSON.stringify({ nodes: doc.nodes, edges: doc.edges }, null, 2))
    setIsPreview(false)
  }

  const loadSchema = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch('/api/v1/topology/schema', { credentials: 'same-origin' })
      if (!res.ok) {
        setError(await readError(res))
        return
      }
      setDoc((await res.json()) as SchemaDoc)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load schema')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void loadSchema()
  }, [loadSchema])

  const handleGenerate = async () => {
    if (!prompt.trim()) return
    setGenerating(true)
    setError(null)
    setNotice(null)
    try {
      const res = await fetch('/api/v1/topology/schema/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'same-origin',
        body: JSON.stringify({ prompt: prompt.trim() }),
      })
      if (!res.ok) {
        setError(await readError(res))
        return
      }
      const data = (await res.json()) as GenerateResponse
      setJsonText(JSON.stringify({ nodes: data.nodes, edges: data.edges }, null, 2))
      setIsPreview(true)
      setNotice(
        data.note ??
          'Preview generated — review the JSON below, then click Apply to make it the live topology.',
      )
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  const handleExtraGenerate = async () => {
    if (!extraGenerator) return
    setExtraGenerating(true)
    setError(null)
    setNotice(null)
    try {
      const data = await extraGenerator.run()
      setJsonText(JSON.stringify({ nodes: data.nodes, edges: data.edges }, null, 2))
      setIsPreview(true)
      setNotice(
        data.note ??
          'Preview generated from your services — review the JSON below, then click Apply to make it the live topology.',
      )
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed')
    } finally {
      setExtraGenerating(false)
    }
  }

  const handleSyncLive = async () => {
    setSyncing(true)
    setError(null)
    setNotice(null)
    try {
      const res = await fetch('/api/v1/topology/schema/sync-live', {
        method: 'POST',
        credentials: 'same-origin',
      })
      if (!res.ok) {
        setError(await readError(res))
        return
      }
      const data = (await res.json()) as GenerateResponse
      setJsonText(JSON.stringify({ nodes: data.nodes, edges: data.edges }, null, 2))
      setIsPreview(true)
      setNotice(
        data.note ??
          'Synced from live infrastructure — review the JSON below, then click Apply to make it the live topology.',
      )
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Sync failed')
    } finally {
      setSyncing(false)
    }
  }

  const handleApply = async () => {
    setApplying(true)
    setError(null)
    setNotice(null)
    let parsed: { nodes: SchemaNodeInput[]; edges: SchemaEdgeInput[] }
    try {
      parsed = JSON.parse(jsonText)
    } catch {
      setError('The editor does not contain valid JSON. Fix the syntax and try again.')
      setApplying(false)
      return
    }
    try {
      const res = await fetch('/api/v1/topology/schema', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'same-origin',
        body: JSON.stringify({ nodes: parsed.nodes, edges: parsed.edges }),
      })
      if (!res.ok) {
        setError(await readError(res))
        return
      }
      setDoc((await res.json()) as SchemaDoc)
      setNotice('Applied — the platform topology now uses this custom schema.')
      onApplied?.()
      setTimeout(() => setNotice(null), 6000)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Apply failed')
    } finally {
      setApplying(false)
    }
  }

  const handleReset = async () => {
    setApplying(true)
    setError(null)
    setNotice(null)
    try {
      const res = await fetch('/api/v1/topology/schema/reset', {
        method: 'POST',
        credentials: 'same-origin',
      })
      if (!res.ok) {
        setError(await readError(res))
        return
      }
      setDoc((await res.json()) as SchemaDoc)
      setNotice('Reverted to the auto-discovered topology.')
      setTimeout(() => setNotice(null), 6000)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Reset failed')
    } finally {
      setApplying(false)
    }
  }

  return (
    <div className="space-y-6">
      {error && (
        <div
          className="flex items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-500"
          role="alert"
          data-testid="topology-error-banner"
        >
          <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
          <span className="text-sm">{error}</span>
        </div>
      )}
      {notice && !error && (
        <div
          className="flex items-start gap-2 rounded-lg border border-green-500/30 bg-green-500/10 p-3 text-green-600"
          data-testid="topology-success-banner"
        >
          <CheckCircle className="h-4 w-4 mt-0.5 shrink-0" />
          <span className="text-sm">{notice}</span>
        </div>
      )}

      {/* Generate from the services the wizard collected (setup wizard only). */}
      {extraGenerator && (
        <div className="bg-card rounded-lg border border-border p-6">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-1">
            <Network className="h-5 w-5 text-primary" /> {extraGenerator.label}
          </h2>
          <p className="text-sm text-muted-foreground mb-3">{extraGenerator.description}</p>
          <button
            type="button"
            onClick={handleExtraGenerate}
            disabled={extraGenerating || loading}
            data-testid="topology-generate-from-services"
            className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 disabled:opacity-50"
          >
            {extraGenerating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Network className="h-4 w-4" />
            )}
            {extraGenerator.label}
          </button>
        </div>
      )}

      {/* Sync from live infrastructure */}
      <div className="bg-card rounded-lg border border-border p-6">
        <h2 className="text-lg font-semibold flex items-center gap-2 mb-1">
          <RefreshCw className="h-5 w-5 text-primary" /> Sync from live infrastructure
        </h2>
        <p className="text-sm text-muted-foreground mb-3">
          Snapshot what is actually running on this host — the services with a live container and any
          discovered remote hosts — into an editable schema. Shown as a preview; nothing changes until
          you click Apply. Use this to make the Command Center graph match a lite or custom deployment.
        </p>
        <button
          type="button"
          onClick={handleSyncLive}
          disabled={syncing || loading}
          data-testid="topology-sync-live"
          className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 disabled:opacity-50"
        >
          {syncing ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
          Sync from live infrastructure
        </button>
      </div>

      {/* Generate with AI */}
      <div className="bg-card rounded-lg border border-border p-6">
        <div className="flex flex-wrap items-center justify-between gap-2 mb-1">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" /> Generate topology with AI
          </h2>
          <span
            className={`px-2 py-0.5 rounded-full text-xs ${
              mode === 'custom'
                ? 'bg-purple-500/10 text-purple-500'
                : 'bg-muted text-muted-foreground'
            }`}
            data-testid="topology-mode"
          >
            {mode === 'custom' ? 'Custom schema active' : 'Auto-discovered'}
          </span>
        </div>
        <p className="text-sm text-muted-foreground mb-3">
          Describe the architecture you want. The Reasoning Agent (Qwen3-14B) drafts a schema; it is
          validated against the strict shape and shown as a preview below — nothing changes until you
          click Apply.
        </p>
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          rows={3}
          placeholder="e.g. Add a Redis cache between the backend and Neo4j, and put a CDN in front of the frontend."
          data-testid="topology-prompt"
          className="w-full p-3 text-sm bg-background rounded-lg border border-border focus:outline-none focus:ring-2 focus:ring-primary resize-y"
        />
        <button
          type="button"
          onClick={handleGenerate}
          disabled={generating || !prompt.trim()}
          data-testid="topology-generate"
          className="mt-3 flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 disabled:opacity-50"
        >
          {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
          Generate preview
        </button>
      </div>

      {/* Schema JSON editor */}
      <div className="bg-card rounded-lg border border-border p-6">
        <div className="flex flex-wrap items-center justify-between gap-2 mb-2">
          <h2 className="text-lg font-semibold">Schema</h2>
          <div className="flex items-center gap-2">
            {isPreview && (
              <span
                className="px-2 py-0.5 rounded-full text-xs bg-amber-500/10 text-amber-500"
                data-testid="topology-preview-badge"
              >
                Unsaved preview
              </span>
            )}
            <button
              type="button"
              onClick={handleReset}
              disabled={applying || loading}
              className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-muted text-muted-foreground rounded-lg hover:bg-muted/80 disabled:opacity-50"
            >
              <RotateCcw className="h-3.5 w-3.5" /> Reset to discovered
            </button>
            <button
              type="button"
              onClick={handleApply}
              disabled={applying || loading}
              data-testid="topology-apply"
              className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 disabled:opacity-50"
            >
              {applying ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{' '}
              Apply
            </button>
          </div>
        </div>
        {loading ? (
          <div className="flex items-center justify-center py-10">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <textarea
            value={jsonText}
            onChange={(e) => {
              setJsonText(e.target.value)
              setIsPreview(false)
            }}
            rows={18}
            spellCheck={false}
            data-testid="topology-json"
            className="w-full p-3 text-xs font-mono bg-background rounded-lg border border-border focus:outline-none focus:ring-2 focus:ring-primary resize-y"
          />
        )}
        <p className="text-xs text-muted-foreground mt-2 flex items-start gap-1">
          <Info className="h-3 w-3 mt-0.5 shrink-0" />
          {`Nodes: {id, label, kind, tier, port?, description?}. Edges: {source, target, relationship, kind}. Allowed kinds: ${ALLOWED_KINDS}. Relationships: DEPENDS_ON, SHIPS_TELEMETRY. A malformed schema is rejected (never applied); you can always Reset to the auto-discovered topology.`}
        </p>
      </div>
    </div>
  )
}
